service:
  name: api-test
  awsKmsKeyArn: arn:aws:kms:ap-southeast-1:209826661801:key/f204d1be-4b43-4759-afbd-4a5218401ffa
  # awsKmsKeyArn: arn:aws:kms:us-east-1:209826661801:key/b73e9471-cb3f-4ad6-b631-76f17d1979bd

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  customDomain:
    domainName: ${env:DOMAIN_NAME}
    basePath: "(none)"
    stage: ${env:STAGE}
    certificateName: "apsls.carsome.my"
    createRoute53Record: true
    envFiles: #YAML files used to create .env file
      - env.yml
    envEncryptionKeyId: #KMS Key used for encrypting values
      dev: ${env:AWS_KMS_KEYID} #Key used for development-stage

package:
  exclude:
    - node_modules
  include:
    - dist

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:AWS_ZONE}

webpackIncludeModules:
  forceInclude:
    - mysql
    - mysql2
    - sequelize

functions:
  pokemonFunc:
    handler: index.handler
    events:
      - http:
          path: pokemon
          method: get
      - http:
          path: pokemon/{id}
          method: get
      - http:
          path: pokemon
          method: post
      - http:
          path: pokemon/{id}
          method: put
      - http:
          path: pokemon/{id}
          method: delete