service:
  name: api-diff
  awsKmsKeyArn: arn:aws:kms:ap-southeast-1:209826661801:key/f204d1be-4b43-4759-afbd-4a5218401ffa
  # awsKmsKeyArn: arn:aws:kms:us-east-1:209826661801:key/b73e9471-cb3f-4ad6-b631-76f17d1979bd

plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-express
  - serverless-offline

custom:
  customDomain:
    domainName: apsls.carsome.my
    basePath: "(none)"
    # stage: ${env:STAGE}
    stage: ${self:provider.stage}
    certificateName: "apsls.carsome.my"
    createRoute53Record: true
    # dotenv:
    #   path: ./.env
    #   basePath: ./

package:
  exclude:
    - node_modules
  include:
    - dist

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:AWS_REGION}
  # region: ap-southeast-1

webpackIncludeModules:
  forceInclude:
    - mysql
    - mysql2
    - sequelize

functions:
  pokemonFunc:
    handler: index.handler
    events:
      - http:
          path: pokemon
          method: get
      - http:
          path: pokemon/{id}
          method: get
      - http:
          path: pokemon
          method: post
      - http:
          path: pokemon/{id}
          method: put
      - http:
          path: pokemon/{id}
          method: delete